services:
  postgres_db:
    image: postgres:16-alpine
    container_name: grocademy_postgres_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: grocademy_dev
      POSTGRES_USER: grocademy_user
      POSTGRES_PASSWORD: grocademy_password
    ports:
      - '5433:5432'
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U grocademy_user -d grocademy_dev']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  postgres_db_data: